version: '2'
services:
  postgres-db:
    image: postgres
    ports:
      - '5432:5432'
    env_file:
      - '${ENV:-dev}.env'
      - ./docker-secrets/db.env

  redis:
    container_name: redis
    image: 'redis:alpine'
    ports:
      - '6379:6379'

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - PORT=8083
    ports:
      - "8082:8083"



  